### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by arrchana** [toobaz/ipynb_output_filter#10] opened 2016-06-26 14:32 UTC
Hi,

Thanks a lot for the very clear description of the steps and the script. However, it doesn't seem to be working for me. I have enabled it globally, and yet, it detects changes when just the "execution_count" in my ipynb in my repo changes. I have followed your steps exactly as stated. Please provide some inputs to fix it.

**Comment by toobaz** [comment] 2016-06-27 07:28
Uhm... hard to guess what's happening. The first thing I would try to do is

`cat your_notebook.ipynb | /the/path/to/ipynb_output_filter.py > out.ipynb`

(the path should be exactly the one in `~/.gitconfig`)

and then in 

`diff your_notebook.ipynb out.ipynb`

you should see all the `"execution count": 35` become `"execution count": null`. Does this work?

**Comment by arrchana** [comment] 2016-06-27 07:30
Sure! Let me try this and get back to you. Thanks :)

**Comment by arrchana** [comment] 2016-06-27 13:27
My execution_count does become null and my outputs become empty lists. Please find attached my input notebook and output notebook. 

I don't know why git doesn't ignore it. When I execute a cell twice and save/checkpoint the notebook, my git status shows that the ipynb has changed. Could you please provide any other suggestions? Thanks!
[ipynbfiles.zip](https://github.com/toobaz/ipynb_output_filter/files/334932/ipynbfiles.zip)

**Comment by ghost** [comment] 2016-07-28 17:46
Hello, I am experiencing the same problem as @arrchana .

**Comment by toobaz** [comment] 2016-07-28 18:10
@arrchana @RECVD

Just to understand: do you have something in `git diff`? Or does the file only show in `git status`?

In the second case... OK, I understand what you mean... but I never found a solution! And I think the only solution would be to fix `git`, which infers in some way that there was a change.

**Comment by ghost** [comment] 2016-07-28 18:16
@toobaz 

For me at least, `git diff` comes out empty, the changes only show in `git status`.  It definitely seems that the problem is on our end, not yours... apparently its pretty commonly a line endings thing, which makes sense as I'm working on windows.  As of yet I still haven't figured it out yet.  Either way I appreciate the quick response.

**Comment by toobaz** [comment] 2016-07-28 19:19
Just to clarify: this does happen in Linux too, but this script has no power to solve this. See for instance [this SO answer](http://stackoverflow.com/a/19809121).

@arrchana : let me know if you also have an empty `git diff`

**Comment by toobaz** [comment] 2019-06-30 23:57
The problem indeed seems to be in git - closing.

**Closed as completed by toobaz** 2019-06-30 23:57 UTC
